package-lock.json, package.json, src-tauri/tauri.conf.json
- Other, please describe: Update package name and version number
=> chore: updating package name and version number

package-lock.json, package.json, src-build/downloadNode.js
feat: initial code to download node based on operating system  and architecture
chore: sonar lint fix
fix: sonar security for unzip
chore: fix for sonar code smell
=> feat: script to download nodejs

package-lock.json, package.json, src-build/downloadNode.js, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
- Feature
add support to bundle node as a resource
=> chore: add support to bundle node as resource

src-build/downloadNode.js
- Bugfix 
windows build faliure
=> fix: windows build faliure

.github/workflows/tauri-build.yml, src-build/cleanNode.js, src-build/downloadNode.js, src-build/utils.js, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
- Feature
adding support for sidecar Tauri
=> Feat: adding support for sidecar tauri

src-tauri/app/hello.js, src-tauri/src/main.rs
- Feature
initial code to execute node from sidecar
=> feat: initial code to execute node from sidecar

.github/workflows/tauri-build.yml, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
=> chore: windows package update for tauri

.gitignore, README.md, package-lock.json, package.json, src-build/clonePhoenix.js, src-build/createDistReleaseConfig.js, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
We use [Tauri](https://tauri.app/) as our app shell. We maintain the [phcode-tauri-shell](https://github.com/phcode-dev/phoenix-desktop) and
[phcode static website](https://github.com/phcode-dev/phoenix) code in two separate repositories. This 
separation is intended to simplify development by distinctly isolating the shell and phcode. For instance,
if you are solely developing the shell internals, you can always construct an empty tauri app without having to build phoenix.
Follow the below
instructions to set up development environment.
1. Setup [node and npm 16+](https://nodejs.org/en/download/).
2. Setup [tauri prerequisites]( https://tauri.app/v1/guides/getting-started/prerequisites/) for your platform.
3. Setup Install gulp globally once with `npm install -g gulp-cli` (use `sudo npm …
=> feat: release build generation scripts

.github/workflows/tauri-build.yml
feat: support for mac signing from github workflow
=> feat: support for mac signing from github workflow

.github/workflows/update-phcode-build.yml
fix https://github.com/phcode-dev/phoenix-desktop/actions/runs/5631820755/job/15259164300#step:6:65
=> fix: typo Cargo.toml

.github/workflows/tauri-build.yml
Enable nsis installer as default in Windows
=> feat: enable nsis for windows

.github/workflows/tauri-build-dev.yml, .github/workflows/tauri-build-prod.yml, .github/workflows/tauri-build-staging.yml, src-tauri/Cargo.lock
app image not rendering video in Linux in GitHub action
=> fix: app image not rendering video in linux

src-tauri/src/init.rs, src-tauri/tauri.conf.json
* fix caash in windows, to test in mac.
* Set product name as Experimental build for default builds
=> fix: crash on startup in mac and windows

src-tauri/Cargo.lock, src-tauri/Cargo.toml
Saving any file was not happening properly.
Fixed by Tauri update: https://github.com/tauri-apps/tauri/issues/7973
=> fix: tauri file corruption on write issue

package-lock.json, package.json, src-build/downloadNodeBinary.js
What kind of change does this PR introduce? The build was failing due to throttling from npmjs.org. this code will fix throttling as we are caching the node to GitHub release
=> Fix nodejs download faliure

.github/workflows/prod-desktop-mac-m1-tests-on-pull.yml, .github/workflows/tauri-build-prod.yml, src-tauri/src/main.rs
Intel macs will be used for staging and dev
only on prod push expensive m1 macs will be used.
=> Use M1 macs for prod build

src-tauri/license/agpl, src-tauri/tauri.conf.json
This PR will show licence for windows and MAC installers in english
=> License Add licence to installers in windows and mac

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
https://discord.com/channels/616186924390023171/1192844593557950474
=> fix: f10 keydown events not working in linux

src-build/mac/filesToSign
https://github.com/phcode-dev/phoenix-desktop/actions/runs/7498838472/job/20420419137
=> fix: mac notarization fail

src-build/win/reg_gen.js
Added support for install and uninstall registry entries
=> feat: added install script for installation and uninstallation

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/Info.plist, src-tauri/src/main.rs
update code to listen open file in mac
=> feat: make changes to support context menu in Mac

src-build/win/reg_gen.js, src-tauri/src/bundle/windows/nsis/installer.nsi
open as phcode project in windows
=> fix: open as phcode project in windows

src-build/win/reg_gen.js, src-tauri/src/bundle/windows/nsis/installer.nsi
=> fix: open with  phoenix code Windows

docs/linux/installer.sh
add error handling for install linux script
=> chore: add error handling for install linux script

docs/linux/installer.sh
=> chore: add retry to wget

docs/linux/installer.sh
adding partial retry while downloading binary
=> chore: adding partial retry while downloading binary and binary name to phcode

src-build/ci-createDistReleaseConfig.js, src-build/createDistReleaseConfig.js, src-build/utils.js, src-tauri/Cargo.lock, src-tauri/src/main.rs, src-tauri/tauri.conf.json
Explanation: https://github.com/phcode-dev/phoenix/issues/1243
=> chore: add hidden window that handles health data due to phtauri custom protocol

docs/linux/installer.sh
Pointing to prod build in linux
=> chore: Pointing to prod build in linux

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
fix: https://discord.com/channels/616186924390023171/1205899594157002793
=> fix: open in default browser with external crate

src-tauri/src/main.rs
maybe setting a cwd as temp folder may help?
=> fix: maybe cannot open path of the current working directory: Permission

docs/linux/installer.sh, src-tauri/tauri.conf.json
=> Feat: enable debian bundles

src-tauri/src/bundle/linux/deb/main.desktop.download, src-tauri/tauri.conf.json
=> chore: fixing mime type for desktop

.github/workflows/tauri-build-dev.yml
change dev build machine to ubuntu-20.04
=> chore: change dev build machine to ubuntu-20.04

.github/workflows/tauri-build-dev.yml, .github/workflows/tauri-build-prod.yml, .github/workflows/tauri-build-staging.yml, src-build/linux/install-readme.txt
For people who downloaded the linux bins and are adventurous
=> ci: add readme.txt for linux binary distributions

docs/linux/installer.sh
Bug fixes and enhancement of Linux installer
=> Linux installer

docs/linux/installer.sh
chore: updating colours for messages in echo for linux install
=> chore: updating colours for messages in echo for linux install

src-tauri/src/main.rs
This is needed for multi window storage sync with `phstore`
=> feat: add inmemory key val map in tuari for phstore

docs/linux/installer-latest-experimental-build.sh
=> fix: check for ui session

docs/linux/installer-latest-experimental-build.sh, docs/linux/installer-pre-prod.sh
remove default file association for html and folder
=> fix: remove default file association for html and folder

docs/linux/installer.sh
installer was not launching repair mode when launched from wget
=> fix: installer was not launching repair mode when launched from wget

.github/workflows/desktop-linux-test-pull.yml, .github/workflows/desktop-mac-m1-test-pull.yml, .github/workflows/desktop-mac-test-pull.yml, .github/workflows/desktop-windows-test-pull.yml, .github/workflows/prod-desktop-tests-on-pull.yml, .github/workflows/staging-desktop-tests-on-pull.yml, .github/workflows/tauri-build-dev.yml, .github/workflows/tauri-build-prod.yml, .github/workflows/tauri-build-staging.yml, .github/workflows/update-phcode-build.yml
update gh workflow to authenticate gh api
=> fix: update gh workflow to authenticate gh api

src-tauri/Cargo.lock
=> chore: cargo update

docs/linux/installer.sh
adding support for kali Linux in installer script
=> feat: adding support for kali linux

docs/linux/installer.sh
Fedora40 was shipped with wget version 2. version 2 of wget is not backward compatible with version 1 of wget. This PR fix the broken installer in Fedora40
=> fix: installer was failing in Fedora 40

docs/linux/installer.sh
The progress bar was not working for Linux installer. This is a regression caused by previous commit
=> fix: progress bar not working for linux installer

src-tauri/Cargo.lock, src-tauri/src/main.rs
Related to : https://github.com/phcode-dev/phoenix-desktop/issues/380
=> feat: add get_process_id tauri api

docs/linux/installer.sh
installation was aborting in the fedora while installing dependencies in the fedora40
=> fix: installation was aborting in fedora

docs/linux/installer.sh
Not supported notification for Ubuntu 24.04
=> chore: notification for not supported in Ubuntu 24.04

docs/linux/installer.sh
=> chore: inital code for Ubuntu 24.04

package-lock.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
Address: https://github.com/orgs/phcode-dev/discussions/1613
=> feat: add move_to_trash api

docs/linux/installer.sh
update was failing in ubuntu 24.04 if it was upgraded from 23
=> fix: update was failing in ubuntu 24.04 if it was upgraded from 23

docs/linux/installer.sh
=> feat:  add support for lubuntu 24.04

.github/workflows/desktop-mac-m1-test-pull.yml
=> fix: mac worker failing

docs/linux/installer.sh
icon not shown in task manager in ubuntu 24.04
=> fix: icon not shown in task manager in ubuntu 24.04

docs/linux/installer.sh
- Bugfix - installation was broken in Fedora
- No
1. run the installer script in fedora40
=> fix: installation was broken in fedora

src-tauri/tauri.conf.json
=> chore: update certificate thumprint

docs/linux/installer.sh
=> fix: support for linux mint 22

docs/linux/installer.sh
=> fix:added support for kali linux

docs/install.json
For listing chrome app in phcode.io website
=> chore: add chrome_os play store link

src-tauri/src/main.rs
Address False positive of Kaspersky detects phnode.exe and index.js as trojan horse https://github.com/phcode-dev/phoenix/issues/1821
Kaspersky is terating the background node process we use as a trojan horse if it opens a URL. We are onboarding to Kaspersky trusted applications program via kaspersky allowed lists to prevent this in the future. 
This is an interim mitigation for the time being.
=> chore: add _open_url_in_browser_win API

src-build/ci-createDistReleaseConfig.js, src-tauri/tauri.conf.json
fixes: https://github.com/phcode-dev/phoenix-desktop/issues/535
=> fix: long product names in windows

src-build/ci-createDistReleaseConfig.js, src-tauri/tauri.conf.json
fix https://github.com/phcode-dev/phoenix-desktop/issues/535
=> fix: long package names in windows open with options

docs/linux/installer-latest-experimental-build.sh, docs/linux/installer.sh
Fixes: https://github.com/orgs/phcode-dev/discussions/1896
=> fix: In some linux distoros, attaching an app to inode will take it as default

docs/linux/installer.sh
installer not working for linux mint 22.1
=> fix: installer not working for linux mint 22.1

docs/linux/installer.sh
=> feat: adding suppor for debian 13
