phcode-dev/phoenix-desktop

.gitignore, entitlements.plist, src-tauri/tauri.conf.json
In an effort to better support Linux, we have made the decision to distribute the application solely through AppImage. This approach ensures broader compatibility across various Linux distributions and tackles potential dependency issues. Key motivations behind this decision include:
* AppImage updates are supported by Tauri, while DEB updates are currently not.
* At present, Tauri supports only Debian packages, which is not optimal for all Linux distributions.
* AppImage conveniently packages all dependencies, circumventing the classic 'Dependency hell' issue.
To enhance user experience, we will provide an easy mechanism to create shortcuts to the AppImage, enabling our app to be listed conveniently in GNOME/KDE applications folders. We are also considering the implementation of a …
=> build: remove dmg builds in ubuntu, package media libs and add macos entitlements

src-build/downloadNode.js, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/tauri.conf.json
1. Enable dev tools in release builds
2. Also updated to use unlink sync if node down,load fail during build step
3. Add js custom API to toggle dev tools from window
```js
invoke("toggle_devtools", {});
```
=> feat: enable dev tools in release builds

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/boot_config.rs, src-tauri/src/init.rs, src-tauri/src/main.rs, src-tauri/src/utilities.rs, src-tauri/tauri.conf.json
Implemented functionality to resize the window to its last known size on application startup, if available.
* If the last known size is not available, the window will be set to a preferred size that ensures the app looks good (an arbitrary size obtained through manual testing and media queries for the new project window).
* If the preferred size exceeds the screen size, the window will be maximized to fit the available space.
=> feat: resize window on startup to last known size

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
Phcode requires extensive system access, and the things we cant do, we should allow our extensions to do. so whitelisting all tauri apis for extensibility and development uses.
We will later have our own sandboxing models for extensions for security.
=> feat: allow all tauri apis as phcode is a devtool

package.json, src-build/ci-createDistReleaseConfig.js, src-build/constants.js, src-tauri/Cargo.lock, src-tauri/tauri.conf.json
Else, all stages will use the same browser storage like local storage / indexed db and will cross contaminate installed builds with dev build data.
=> ci: change bundle id based on stage to create different browser webview profiles for stage

src-build/downloadNode.js
fail the build if the download node from npm failed
=> fix: fail build if github action node from npm failed

src-tauri/src/main.rs
related: https://github.com/phcode-dev/phoenix/pull/1136
=> refactor: tauri already has os.tempdir api, so removing our impl

src-tauri/src/init.rs, src-tauri/src/main.rs, src-tauri/src/utilities.rs
1. The window size to restore was inner size. But we used outer size before which caused progressive launches to increase in window size.
2. More logs only in debug builds
=> fix: window size jumps on successive launches

src-tauri/src/main.rs
Related: https://github.com/tauri-apps/tauri/issues/4062
=> feat: show_in_folder api to open file/folder in system explorer

src-build/ci-createDistReleaseConfig.js, src-build/createDistReleaseConfig.js, src-build/createDistTestReleaseConfig.js, src-build/createSrcReleaseConfig.js, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/tauri.conf.json
When we install a version say `1.1.1`, we usually set cache HTTP headers so that we cache the HTTP requests for a year.
So when we upgrade to v1.1.2, it may serve the old caches HTML files from the browser cache instead of the new files.
So to burst the cache, we prepend the version string to base URLs like `http://localhost/v1.1.1/`
=> chore: cache bursting using version prefixes

README.md, package.json, src-build/createDemoReleaseConfig.js
If you dont want to build phcode and just build a demo app with similar config as phcode(You may do this
if you are working on the release generation or build tooling and don't want to wait for phcode to build
every time you want to test the build). Just run this command:
```bash
npm run tauriBuildDemoApp
```
=> build: npm run tauriBuildDemoApp to build demo app

src-build/ci-createDistReleaseConfig.js, src-build/createDistReleaseConfig.js, src-build/createDistTestReleaseConfig.js, src-build/createSrcReleaseConfig.js, src-tauri/src/main.rs, src-tauri/tauri.conf.json
tauri bug in windows for custom protocol that redirects `fetch(https://phcode.site)` to our rust custom protocol handler as `phcode://site`
used phtauri as it doesnt seem likely to conflict with any domains
=> chore: change phcode protocol to phtauri as its interfering with phcode.site and other domains in windows

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/boot_config.rs, src-tauri/src/init.rs, src-tauri/src/main.rs
Earlier we didnt know about this tauri plugin, so migrating away from our own impl.
Tauri's impl is much more consistant and fixes bugs. Now the restore will
1. Remember windows positions and sizes for every window opened.
2. remebers which display to use if there are multiple displays. our impl didnt handle this.
3. The windows posisioning is now much more consistant than our impl and feels aligned with the os window placement logic.
=> refactor: use tauri window position restore plugins instead of self impl

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
After this , call in windows, linux and mac platforms for webview zoom
```js
await __TAURI__.tauri.invoke("zoom_window", {scaleFactor:1.2});
```
Fixes: https://github.com/phcode-dev/phoenix/issues/1168
reference: https://docs.rs/tauri/latest/tauri/window/struct.Window.html
=> feat: native window webview zoom rust-JS API

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
GUI apps on macOS and Linux do not inherit the $PATH from your shell dotfiles (.bashrc, .bash_profile, .zshrc, etc). Check out Tauri's [fix-path-env-rs](https://github.com/tauri-apps/fix-path-env-rs) crate to fix this issue.
=> fix: GUI apps on macOS and Linux do not inherit the PATH from your shell dot files

src-tauri/tauri.conf.json
reinstating media codes as live previewing video is a workflow that the user would expect to be working. So a 2 second load pause for media libraries on click of video is acceptable.
We will remove all videos in phoenix desktop linnux builds in new project window and default project
=> build: add media codecs in linux

src-build/constants.js
Tauri uses the name to determine install/appdata folder, not just the id. So we will not be able to updrage the prod builds if we suffix names like beta/rc etc. That has to be done within phcode codebase app_name directly.
=> fix: prod release name is always phoenix code

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
`window.__TAURI__.tauri.invoke('_get_clipboard_files')`  
returns and array of file paths if file(s) have been copied to clipboard
else returns null
=> feat: add support for getting copied files from clipboard

src-tauri/tauri.conf.json
When we enable the tauri feature to enable drop files in tauri  window, it creeates the following problems
1. in windows browser drag drop events are disabled completely. This means that user cannot move files in files panel or move code with drag drop which is a critical in-editor workflow break.
2. In mac too, drag events work, but browser drop events are never received causing an evn greater inconsistency.
3. in linux most features work with no issues noted
So, in favor of in editor workflows, users can no-longer drop files from windows explorer/os finder into phoenix app to open the file. Users have to use `file menu>open` to open a file or folder. or `right click and use open with phoenix code` in future till tauri fixes this issue at their end.
start reference: …
=> fix: disable tauri file drop as it disables browser drag-drop

.github/workflows/tauri-build-dev.yml, .github/workflows/tauri-build-prod.yml, .github/workflows/tauri-build-staging.yml
This adds a new job that runs on m1 mac, that does npm install on m1 macs for src-node folder, and then gzip the folder and uploads it as a github artifact to consume for the next step(which runs on an intel mac).
=> ci: m1 macs node modules generation

.github/workflows/tauri-build-dev.yml, .github/workflows/tauri-build-prod.yml, .github/workflows/tauri-build-staging.yml
cutting it too close.
Eg: https://github.com/phcode-dev/phoenix-desktop/actions/runs/7721463216/job/21048101258
=> ci: increase release build gen timeout to 60 mins

.github/workflows/tauri-build-staging.yml
adding support for free m1 runner in devo
=> feat: adding support for free m1 runner in devo

src-tauri/Cargo.lock, src-tauri/src/main.rs
it appears that `webbrowser` crate and tauri api doenst open the url in prod app image, if firefox is set as the default browser.
()Maybe tauri is using `webbrowser` create inernally? 
Anyways moved to `xdg-open` for linux.
=> fix: linux open url with firefox usind xdmg

src-tauri/Cargo.lock, src-tauri/src/main.rs
`phcode --runVerify` will exit with code 0 if run success without launching any ui.
Helpful to be used by linux installer to see if the app loaded successfully with all libs
=> build: add --runVerify cli command to see if app load success

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
We needed `open_url_in_browser` api in linux as linux was not linuxing with app images. Since we are deprecating appimages and moving to native linux binaries/bash installers, this is no longer needed, neither did it work eventually.
=> refactor: remove unused open url in browser api

src-tauri/tauri.conf.json
update the timestamp URL to global sign and see if it fixes warning in edge
=> fix: update timestamp url to global sign

docs/linux/installer-pre-prod.sh
running installer from non-gui sessions was failing
=> fix: running installer from non-gui sessions was failing

src-tauri/tauri.conf.json
Mainly to be used by mac update installer, where we cant rely on tauri apis or node to be present as the underlying binaries are being rewritten.
=> chire: add recursive-rm-unix private command

src-tauri/tauri.conf.json
This is needed for mac auto updates as the earlier update flow used to extract the file at node side and then copy it on exit. This created a problem where the downloaded app(which is yet to be installed) would register into macs `open with` apps and show up in finder `open with` as 2 entries for phoneix app.
=> feat: add untar-unix command

src-tauri/src/main.rs
And extra `/` was being seen in the file path bar in Linux. See image below:
=> fix: extra / is path when show in os files is done

package-lock.json
The new tauri merge from rennovate did not setup the optional tauri cli dependency correctly as it only patched the package-lock with the dep and not merge in optional deps. For tauri merges, we should do the following: (Platform is'nt relavant, just do it in any of win/mac/linux)
1. rm -rf node_modules
2. rm package-lock.json
3. npm install
Not check in the generated package lock.
=> fix: package-lock was inconsistant in mac platfrom x64

docs/linux/installer.sh
Added code to install missing gtk libs for ubuntu24.04
=> feat: support for ubuntu 24.04

docs/linux/installer.sh
code clean up and documentation
=> chore: code clean up and doccumentation

.github/workflows/desktop-mac-test-pull.yml
This reverts commit 703ff1e273ef9242187e70d37a40ffd1e63b5193.
Revert "chore(deps): update dependency macos to v14"
=> Revert "chore(deps): update dependency macos to v14"

docs/linux/installer.sh
=> Chore: code cleanup

docs/linux/installer.sh
adding check for arch for Linux installer
=> chore:adding check for arch for linux installer

.github/workflows/updateNotification.js
Continuation of https://github.com/phcode-dev/phoenix-desktop/pull/505
This updates github actions to also include chrome app link on new release. the other pr was for current release manually added.
=> chore: add chrome_os play store link

docs/linux/installer.sh
The install script failed when the user copied and pasted the script from the website to the terminal and ran in the shell.
This pull request fixes it
=> fix: linux installer was failing in arch

src-tauri/Cargo.toml
https://github.com/phcode-dev/phoenix-desktop/pull/537 didnt work. so this
=> fix: long package names in windows open with options

.github/workflows/desktop-linux-test-pull.yml, .github/workflows/prod-desktop-tests-on-pull.yml, .github/workflows/staging-desktop-tests-on-pull.yml, .github/workflows/tauri-build-dev.yml, .github/workflows/tauri-build-prod.yml, .github/workflows/tauri-build-staging.yml, .github/workflows/update-phcode-build.yml, docs/linux/installer.sh
installer broke in ubuntu 24.10
=> fix: installer broken in ubuntu 24.10

docs/linux/installer.sh
=> fix: installer borken in ubuntu 25
